name: HV ECOM FE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set Node.js memory limit
        run: echo "NODE_OPTIONS=--max-old-space-size=4096" >> $GITHUB_ENV

      - name: Install project dependencies
        run: npm ci

      - name: Build project
        run: NODE_OPTIONS=--max-old-space-size=4096 npm run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/heads/main')
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HVECOM_SERVER_IP }}
          username: ${{ vars.HVECOM_SERVER_USERNAME }}
          key: ${{ secrets.HVECOM_SERVER_PRIVATE_KEY }}
          port: ${{ vars.HVECOM_SSH_PORT || 22 }}
          script: |
            # Load NVM to set up Node.js and npm
            source ~/.nvm/nvm.sh

            # Navigate to the project directory
            cd /var/www/project/hv-prod-fe

            # Pull the latest changes
            git pull origin main

            # Install dependencies
            npm ci

            # Build the project
            npm run build

            # Install PM2 if not already installed
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi

            # Reload or start the PM2 process
            pm2 reload ecosystem.config.cjs --env production || pm2 start ecosystem.config.cjs --env production

            # Save the PM2 process list
            pm2 save --force