name: HV ECOM FE

on:
    push:
        branches:   [main] # trigger when push to main branch
    pull_request:
        branches:   [main]
    
jobs:
    build-and-test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [18, 20]
      steps:
        - uses: actions/checkout@v3
        - name: install node ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm' 
        - name: install project dependencies 
          run: npm ci
        - name: build project
          run: NODE_OPTIONS=--max-old-space-size=4096 npm run build

    deploy:
      needs: build-and-test
      runs-on: ubuntu-latest
      if: contains(github.ref, 'refs/heads/main')
      steps:
        - uses: appleboy/ssh-action@master
          with:
            host: ${{ vars.HVECOM_SERVER_IP }}
            username: ${{ vars.HVECOM_SERVER_USERNAME }}
            # key: ${{ secrets.HVECOM_SERVER_PRIVATE_KEY }}
            key: ${{ secrets.HV_ECOM_SERVER_SECRET_DO }}
            port: ${{ vars.HVECOM_SSH_PORT || 22 }}
            script: |
                # Load NVM to set up Node.js and npm 
                source ~/.nvm/nvm.sh 

                # Navigate to project directory
                cd /var/www/project/hv-prod-fe

                # Fetch latest changes
                git fetch origin
                git pull --ff-only origin main  # Safer alternative to reset --hard

                # Install dependencies
                npm ci

                # Build the project
                npm run build 

                # Ensure PM2 is installed
                if ! command -v pm2 &> /dev/null; then
                  npm install -g pm2
                fi

                # Ensure PM2 starts the correct Nuxt output file
                pm2 describe nuxt-app > /dev/null 2>&1
                if [ $? -eq 0 ]; then
                  pm2 reload nuxt-app --update-env
                else
                  pm2 start "node .output/server/index.mjs" --name "nuxt-app"
                fi

                # Save PM2 process list (only needed once)
                # pm2 save --force

                # Ensure PM2 starts on boot
                # pm2 startup systemd -u $USER --hp $HOME


    
    
